### ISSUE TITLE
Simplify module IAM configs

### ISSUE THREAD

**Issue by exequielrafaela** [binbashar/terraform-aws-ec2-basic-layout#17]
### What?

Simplify module IAM configs it should only support:
- instance_profile: The IAM Instance Profile to launch the instance with. Specified as the name of the Instance Profile (https://github.com/binbashar/terraform-aws-ec2-basic-layout/tree/master/examples/ec2-external-instance-profile).
- policy_arn: Attach AWS IAM managed policies to the IAM Role (https://github.com/binbashar/terraform-aws-ec2-basic-layout/blob/5bfd521558eaefa7da85ed4d0a376287e1a0e7d3/examples/ec2-default-instance-profile/main.tf#L90).

Should Remove Code for:
- policy_acctions_list: Action list for EC2 profile IAM Role policy.

### Why? 
* Module IAM support too broad, we'll go for a simplified form that allows the user to extend the permissions of the instance.
* The module should do the minimum (using the least privilege principle) for the instance profile and then simply provide a mechanism for whoever uses the module to extend it or passing an external one via arn / name.

**Comment by binbashdevops** [comment]
## Please consider

### Before
```
  # EC2 IAM Profile (Role + Policies)
  cross_account_roles_resource_arn_list = [
    "arn:aws:iam::${var.dev_account_id}:role/DevOps",
    "arn:aws:iam::${var.shared_account_id}:role/DevOps",
    "arn:aws:iam::${var.dev_account_id}:role/Auditor",
    "arn:aws:iam::${var.shared_account_id}:role/Auditor",
  ]
  policy_acctions_list = [
    "ecr:*",
    "ssm:*",
    "route53:*",
    "s3:ListBucket",
    "s3:PutObject",
    "s3:PutObjectAcl",
    "s3:GetObject",
    "s3:DeleteObject"
  ]
  policy_arn = [
    "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess",
    "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess",
  ]

  tags = local.tags
}
```

### After 
```
  # EC2 IAM Profile (Role + Policies)
  cross_account_roles_resource_arn_list = [
    "arn:aws:iam::${var.dev_account_id}:role/DevOps",
    "arn:aws:iam::${var.shared_account_id}:role/DevOps",
    "arn:aws:iam::${var.dev_account_id}:role/Auditor",
    "arn:aws:iam::${var.shared_account_id}:role/Auditor",
  ]
  policy_arn = [
    "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess",
    "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess",
  ]

  tags = local.tags
}
```

## :warning: CONSIDERATIONS
1. Please update the examples.
2. Make `cross_account_roles_resource_arn_list` as OPTIONAL (fix needed: it should'n depends on `policy_acctions_list`)
